name: Docker Build and Publish

on:
  push:  
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
#    runs-on: self-hosted


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        source .env
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kaillera:$version .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kaillera:$version
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
